name: gen-web CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/**'

jobs:
  deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cp readme.md
        run: cp README.md docs/index.md
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CUSTOM_DOMAIN: optionaldomain.com
          # CONFIG_FILE: folder/mkdocs.yml
          # EXTRA_PACKAGES: build-base
          # # GITHUB_DOMAIN: github.myenterprise.com
          REQUIREMENTS: requirements.txt
