name: Intellij Plugin Build CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'module-assembler-intellij-plugin/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'module-assembler-intellij-plugin/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'

    - name: buildPlugin
      run: cd module-assembler-intellij-plugin &&  ./gradlew buildPlugin
    - name: Upload Plugin
      uses: actions/upload-artifact@v4
      with:
        # name: kmp-android.apk
        path: module-assembler-intellij-plugin/build/distributions/**
