name: Plugin Build CI

on:
  push:
    branches: [ "main" ]
    paths:
       - 'module-assembler-common/**'
       - 'module-assembler-intellij-plugin/**'
       - 'module-assembler-gradle-plugin/**'
       - 'module-assembler-gradle-plugin-kt/**'
  pull_request:
    branches: [ "main" ]
    paths:
       - 'module-assembler-common/**'
       - 'module-assembler-intellij-plugin/**'
       - 'module-assembler-gradle-plugin/**'
       - 'module-assembler-gradle-plugin-kt/**'

jobs:
  intellij-plugin-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup jdk-17
      uses: actions/setup-java@main
      with:
        java-version: 17
        distribution: 'adopt'

    - name: buildPlugin
      run: cd module-assembler-intellij-plugin &&  ./gradlew buildPlugin
    - name: Upload Plugin
      uses: actions/upload-artifact@v4
      with:
        # name: kmp-android.apk
        path: module-assembler-intellij-plugin/build/distributions/**

  gradle-plugin-build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Setup jdk-17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'

      - name: buildPlugin
        run: cd module-assembler-gradle-plugin &&  ./gradlew assemble
      - name: Upload Plugin
        uses: actions/upload-artifact@v4
        with:
          # name: kmp-android.apk
          path: module-assembler-gradle-plugin/build/libs/**

  gradle-plugin-kt-build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3

      - name: Setup jdk-17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'adopt'

      - name: buildPlugin
        run: cd module-assembler-gradle-plugin-kt &&  ./gradlew assemble
      - name: Upload Plugin
        uses: actions/upload-artifact@v4
        with:
          # name: kmp-android.apk
          path: module-assembler-gradle-plugin-kt/build/libs/**
